version: "3.3"

services:
  server:
    build:
      context: ./
    ports:
      - "8050:8050"
    volumes:
      - ./:/dashboard
      - analysisdata:/tmp/airflow/
    ports:
      - "8050:8050"
    entrypoint: "tail -f /dev/null"
volumes:
  analysisdata:
